DROP TABLE IF EXISTS VILLE;
CREATE TABLE IF NOT EXISTS VILLE(
    ID INT PRIMARY KEY NOT NULL,
    NOM_VILLE VARCHAR(30)
);

ALTER TABLE VILLE 
RENAME COLUMN ID TO ID_VILLE;

ALTER TABLE CLIENT 
DROP COLUMN ville;