DROP TABLE IF EXISTS USERS;
CREATE TABLE IF NOT EXISTS USERS (
  USERNAME VARCHAR(25) PRIMARY KEY  NOT NULL,
  PASSWORD VARCHAR(250) NOT NULL,
  ACTIVE INT NOT NULL
);

DROP TABLE IF EXISTS USERS_ROLES;
CREATE TABLE IF  NOT EXISTS USERS_ROLES (
 USERNAME VARCHAR(25) NOT NULL,
  ROLES VARCHAR(20) NOT NULL,
  PRIMARY KEY(USERNAME, ROLES)
);

DROP TABLE IF EXISTS ROLES;
CREATE TABLE IF NOT EXISTS ROLES (
ROLE VARCHAR(20) PRIMARY KEY NOT NULL
);